version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    container_name: chat-redis
    ports:
      - '6379:6379'
    restart: always
