name: 🚀 Deploy Chat App via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to SSH Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose git

            cd ~
            rm -rf app
            git clone https://github.com/YoussefElkasrawy/real-time-chat-api.git app
            cd app

            echo "PORT=${{ secrets.PORT }}" > .env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            echo "ACCESS_TOKEN_EXP=${{ secrets.ACCESS_TOKEN_EXP }}" >> .env
            echo "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}" >> .env

            docker-compose down --volumes --remove-orphans
            docker-compose up --build -d
