name: Build & Deploy Chat App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image with GitHub Secrets
        run: docker build --build-arg PORT=${{ secrets.PORT }} --build-arg NODE_ENV=${{ secrets.NODE_ENV }} --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} --build-arg ACCESS_TOKEN_EXP=${{ secrets.ACCESS_TOKEN_EXP }} --build-arg ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }} -t chat-app .


      - name: Run container (optional test run)
        run: docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} chat-app
