# .github/workflows/deploy.yml
name: Build and Deploy Chat App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Compose Build and Up
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "ACCESS_TOKEN_EXP=${{ secrets.ACCESS_TOKEN_EXP }}" >> .env
        echo "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}" >> .env
        docker-compose up --build -d
